const products = [
  {
    id: 1,
    img: "https://cdn.kyou.id/thumbnail/items/234030-pvc-figure-17-klee-spark-knight-ver-genshin-impact.jpg",
    title: "[Exclusive Sale] PVC Figure 1/7 Klee - S...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    prevPrice: "IDR 2.650.000",
    newPrice: "IDR 2.549.000",
    company: "ReadyStock",
    color: "white",
    category: "exclusive",
    likes: 15,
  },
  {
    id: 2,
    img: "https://cdn.kyou.id/thumbnail/items/102336-hu-tao-ghost-night-lamp-15x14cm-genshin-impact.jpg",
    title: "[Exclusive Sale] Hu Tao Ghost Night...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 580.000",
    newPrice: "IDR 549.000",
    company: "ReadyStock",
    color: "red",
    category: "exclusive",
    likes: 20,
  },

  {
    id: 3,
    img: "https://cdn.kyou.id/thumbnail/items/82990-3rd-release-jumpy-dumpty-klee-mug-genshin-impact-360ml-11x15cm.jpg",
    title: "[Shukaku SALE] Jumpy Dumpty Klee...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 380.000",
    newPrice: "IDR 349.000",
    company: "ReadyStock",
    color: "green",
    category: "exclusive",
    likes: 22,
  },
  {
    id: 4,
    img: "https://cdn.kyou.id/thumbnail/items/247366-ichiban-kuji-figure-gojo-satoru-jujutsu-kaisen-shibuya-incident-vol1-last-one-prize-19cm.jpg",
    title: "[Exclusive Sale] Ichiban Kuji Figure...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 1.950.000",
    newPrice: "DP IDR 1.950.000",
    company: "PreOrder",
    color: "black",
    category: "latest",
    likes: 18,
  },
  {
    id: 5,
    img: "https://cdn.kyou.id/thumbnail/items/243557-lookup-figure-mayuzumi-fuyuko-the-idolmaster-shiny-colors.jpg",
    title: "[Limited Edition] Figure mayuzumi...",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "green",
    category: "Limited",
    likes: 2,
  },
  {
    id: 6,
    img: "https://cdn.kyou.id/thumbnail/items/247367-ichiban-kuji-figure-uruti-one-piece-beast-pirates-tobi-rokusou-a-prize-11cm.jpg",
    title: "[Limited Edition] Ichiban Kuji Figure...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 1.050.000",
    newPrice: "DP IDR 300.000",
    company: "PreOrder",
    color: "black",
    category: "latest",
    likes: 10,
  },

  {
    id: 7,
    img: "https://cdn.kyou.id/thumbnail/items/243556-lookup-figure-serizawa-asahi-the-idolmaster-shiny-colors.jpg",
    title: "[Limited Production] Lookup Figure...",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "white",
    category: "Limited",
    likes: 15,
  },

  {
    id: 8,
    img: "https://cdn.kyou.id/thumbnail/items/106989-feb-2022-release-taroumaru-inazuma-plush-genshin-impact.jpg",
    title: "[Exclusive Sale] Taroumaru Thoma...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 800.000 ",
    newPrice: "IDR 769.000 ",
    company: "ReadyStock",
    color: "green",
    category: "exclusive",
    likes: 20,
  },

  {
    id: 9,
    img: "https://cdn.kyou.id/thumbnail/items/247363-ichiban-kuji-figure-itadori-yuji-jujutsu-kaisen-shibuya-incident-vol1-a-prize-16cm.jpg",
    title: "[Exclusive Sale] Ichiban Kuji Figure...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 560.000",
    newPrice: "DP IDR 100.000",
    company: "PreOrder",
    color: "blue",
    category: "latest",
    likes: 30,
  },

  {
    id: 10,
    img: "https://cdn.kyou.id/thumbnail/items/204312-bloodline-of-combat-tapestry-b-60x40cm-arknigts.jpg",
    title: "[Exclusive Sale] Bloodline of Combat...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 270.000 ",
    newPrice: "IDR 100.000 ",
    company: "BackOrder",
    color: "green",
    category: "latest",
    likes: 15,
  },
  {
    id: 11,
    img: "https://cdn.kyou.id/thumbnail/items/204303-muelsyse-elite-2-ver-shikishi-15x21cm-arknights.jpg",
    title: "[Exclusive Sale] Muelsyse Elite 2 Ver...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 130.000",
    newPrice: "DP IDR 50.000",
    company: "BackOrder",
    color: "red",
    category: "latest",
    likes: 10,
  },
  {
    id: 12,
    img: "https://cdn.kyou.id/thumbnail/items/204304-hoolheyak-elite-2-ver-shikishi-15x21cm-arknights.jpg",
    title: "[Exclusive Sale] Ho'olheyak Elite 2...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 130.000",
    newPrice: "DP IDR 50.000",
    company: "BackOrder",
    color: "black",
    category: "latest",
    likes: 12,
  },
  {
    id: 13,
    img: "https://cdn.kyou.id/thumbnail/items/204305-silence-the-paradigmatic-elite-2-ver-shikishi-15x21cm-arknights.jpg",
    title: "[Exclusive Sale] Silence ELite 2 Ver...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 130.000",
    newPrice: "DP IDR 50.000",
    company: "BackOrder",
    color: "white",
    category: "latest",
    likes: 13,
  },
  {
    id: 14,
    img: "https://cdn.kyou.id/thumbnail/items/204306-lone-trail-oil-filled-acrylic-brick-panel-21x12cm-arknights.jpg",
    title: "[Exclusive Sale] Lone Trail Oil-filled...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 370.000",
    newPrice: "DP IDR 100.000",
    company: "BackOrder",
    color: "black",
    category: "latest",
    likes: 16,
  },

  {
    id: 15,
    img: "https://cdn.kyou.id/thumbnail/items/204298-chen-the-holungday-ten-thousand-mountains-shikishi-15x21cm-arknights.jpg",
    title: "[Exclusive Sale] Ch'en the Holungday: Ten...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 130.000",
    newPrice: "DP IDR 50.000",
    company: "BackOrder",
    color: "green",
    category: "latest",
    likes: 19,
  },
  {
    id: 16,
    img: "https://cdn.kyou.id/thumbnail/items/243541-lookup-figure-kita-ikuyo-bocchi-the-rock.jpg",
    title: "[Limited Edition] Lookup Figure Kita...",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "red",
    category: "Limited",
    likes: 29,
  },
  {
    id: 17,
    img: "https://cdn.kyou.id/thumbnail/items/243542-lookup-figure-yamada-ryo-bocchi-the-rock.jpg",
    title: "Lookup Figure Yamada Ryo - Bocchi the Rock!",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "white",
    category: "Bonus",
    likes: 2,
  },
  {
    id: 18,
    img: "https://cdn.kyou.id/thumbnail/items/243540-lookup-figure-hitori-gotoh-bocchi-the-rock.jpg",
    title: "Lookup Figure Hitori Gotoh - Bocchi...",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "blue",
    category: "Bonus",
    likes: 5,
  },
  {
    id: 19,
    img: "https://cdn.kyou.id/thumbnail/items/153621-raiden-shogun-figure-statue-of-her-excellency-the-almighty-narukami-ogosho-god-of-thunder-11cm.jpg",
    title: "[Shukaku SALE] PVC Figure 1/7 Ganyu - ...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 2.450.000",
    newPrice: "IDR 2.319.000",
    company: "ReadyStock",
    color: "black",
    category: "Bonus",
    likes: 7,
  },
  {
    id: 20,
    img: "https://cdn.kyou.id/thumbnail/items/243543-lookup-figure-ijichi-nijika-bocchi-the-rock.jpg",
    title: "Lookup Figure Ijichi Nijika - Bocchi the Rock!",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "black",
    category: "Revive",
    likes: 8,
  },
  {
    id: 21,
    img: "https://cdn.kyou.id/thumbnail/items/113549-limited-production-nendoroid-venti-genshin-impact.jpg",
    title: "[Shukaku Sale] Nendor...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 720.000",
    newPrice: "IDR 699.000",
    company: "ReadyStock",
    color: "red",
    category: "Revive",
    likes: 9,
  },
  {
    id: 22,
    img: "https://cdn.kyou.id/thumbnail/items/163039-limited-production-nendoroid-traveler-lumine-genshin-impact.jpg",
    title: "[Exclusive Sale] Nendoro...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 1.320.000",
    newPrice: "IDR 1.249.000",
    company: "ReadyStock",
    color: "red",
    category: "exclusive",
    likes: 9,
  },

  {
    id: 23,
    img: "https://cdn.kyou.id/thumbnail/items/140557-limited-production-nendoroid-traveler-aether-genshin-impact.jpg",
    title: "[Shukaku SALE] Nendoro...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 820.000",
    newPrice: "IDR 699.000",
    company: "ReadyStock",
    color: "black",
    category: "Revive",
    likes: 10,
  },
  {
    id: 24,
    img: "https://cdn.kyou.id/thumbnail/items/247371-ichiban-kuji-figure-whos-who-one-piece-beast-pirates-tobi-rokusou-e-prize-12cm.jpg",
    title: "Ichiban Kuji Figure Who's Who - One Pi...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 835.000",
    newPrice: "IDR 200.000",
    company: "PreOrder",
    color: "black",
    category: "latest",
    likes: 10,
  },
  {
    id: 25,
    img: "https://cdn.kyou.id/thumbnail/items/247365-ichiban-kuji-figure-gojo-satoru-jujutsu-kaisen-shibuya-incident-vol1-c-prize-19cm.jpg",
    title: "Ichiban Kuji Figure Gojo Satoru - Jujutsu Kai...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 1.550.000",
    newPrice: "DP IDR 550.000",
    company: "PreOrder",
    color: "black",
    category: "latest",
    likes: 10,
  },
  {
    id: 26,
    img: "https://cdn.kyou.id/thumbnail/items/247369-ichiban-kuji-figure-x-drake-one-piece-beast-pirates-tobi-rokusou-c-prize-12cm.jpg",
    title: "Ichiban Kuji Figure X Drake - One Piece Be...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 795.000",
    newPrice: "DP IDR 200.000",
    company: "PreOrder",
    color: "black",
    category: "latest",
    likes: 10,
  },
  {
    id: 27,
    img: "https://cdn.kyou.id/thumbnail/items/247372-ichiban-kuji-figure-black-maria-one-piece-beast-pirates-tobi-rokusou-f-prize-18cm.jpg",
    title: "[Limited Production] Ichiban Kuji Figure...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 2.350.000",
    newPrice: "DP IDR 900.000",
    company: "PreOrder",
    color: "black",
    category: "latest",
    likes: 10,
  },
  {
    id: 28,
    img: "https://cdn.kyou.id/thumbnail/items/234030-pvc-figure-17-klee-spark-knight-ver-genshin-impact.jpg",
    title: "[Exclusive Sale] PVC Figure 1/7 Klee - S...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 2.650.000",
    newPrice: "IDR 2.549.000",
    company: "ReadyStock",
    color: "white",
    category: "exclusive",
    likes: 10,
  },
  {
    id: 29,
    img: "https://cdn.kyou.id/thumbnail/items/102336-hu-tao-ghost-night-lamp-15x14cm-genshin-impact.jpg",
    title: "[Exclusive Sale] Hu Tao Ghost Night...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 580.000",
    newPrice: "IDR 549.000",
    company: "ReadyStock",
    color: "red",
    category: "exclusive",
    likes: 12,
  },

  {
    id: 30,
    img: "https://cdn.kyou.id/thumbnail/items/82990-3rd-release-jumpy-dumpty-klee-mug-genshin-impact-360ml-11x15cm.jpg",
    title: "[Shukaku SALE] Jumpy Dumpty Klee...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 380.000",
    newPrice: "IDR 349.000",
    company: "ReadyStock",
    color: "green",
    category: "exclusive",
    likes: 13,
  },
  {
    id: 31,
    img: "https://cdn.kyou.id/thumbnail/items/247366-ichiban-kuji-figure-gojo-satoru-jujutsu-kaisen-shibuya-incident-vol1-last-one-prize-19cm.jpg",
    title: "[Exclusive Sale] Ichiban Kuji Figure...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 1.950.000",
    newPrice: "DP IDR 1.950.000",
    company: "PreOrder",
    color: "black",
    category: "latest",
    likes: 14,
  },
  {
    id: 32,
    img: "https://cdn.kyou.id/thumbnail/items/243557-lookup-figure-mayuzumi-fuyuko-the-idolmaster-shiny-colors.jpg",
    title: "[Limited Edition] Figure mayuzumi...",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "green",
    category: "Limited",
    likes: 15,
  },
  {
    id: 33,
    img: "https://cdn.kyou.id/thumbnail/items/247367-ichiban-kuji-figure-uruti-one-piece-beast-pirates-tobi-rokusou-a-prize-11cm.jpg",
    title: "[Limited Edition] Ichiban Kuji Figure...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 1.050.000",
    newPrice: "DP IDR 300.000",
    company: "PreOrder",
    color: "black",
    category: "latest",
    likes: 16,
  },

  {
    id: 34,
    img: "https://cdn.kyou.id/thumbnail/items/243556-lookup-figure-serizawa-asahi-the-idolmaster-shiny-colors.jpg",
    title: "[Limited Production] Lookup Figure...",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "white",
    category: "Limited",
    likes: 17,
  },

  {
    id: 35,
    img: "https://cdn.kyou.id/thumbnail/items/106989-feb-2022-release-taroumaru-inazuma-plush-genshin-impact.jpg",
    title: "[Exclusive Sale] Taroumaru Thoma...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 800.000 ",
    newPrice: "IDR 769.000 ",
    company: "ReadyStock",
    color: "green",
    category: "exclusive",
    likes: 18,
  },

  {
    id: 36,
    img: "https://cdn.kyou.id/thumbnail/items/247363-ichiban-kuji-figure-itadori-yuji-jujutsu-kaisen-shibuya-incident-vol1-a-prize-16cm.jpg",
    title: "[Exclusive Sale] Ichiban Kuji Figure...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 560.000",
    newPrice: "DP IDR 100.000",
    company: "PreOrder",
    color: "blue",
    category: "latest",
    likes: 30,
  },

  {
    id: 37,
    img: "https://cdn.kyou.id/thumbnail/items/204312-bloodline-of-combat-tapestry-b-60x40cm-arknigts.jpg",
    title: "[Exclusive Sale] Bloodline of Combat...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 270.000 ",
    newPrice: "IDR 100.000 ",
    company: "BackOrder",
    color: "green",
    category: "latest",
    likes: 29,
  },
  {
    id: 38,
    img: "https://cdn.kyou.id/thumbnail/items/204303-muelsyse-elite-2-ver-shikishi-15x21cm-arknights.jpg",
    title: "[Exclusive Sale] Muelsyse Elite 2 Ver...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 130.000",
    newPrice: "DP IDR 50.000",
    company: "BackOrder",
    color: "red",
    category: "latest",
    likes: 28,
  },
  {
    id: 39,
    img: "https://cdn.kyou.id/thumbnail/items/204304-hoolheyak-elite-2-ver-shikishi-15x21cm-arknights.jpg",
    title: "[Exclusive Sale] Ho'olheyak Elite 2...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 130.000",
    newPrice: "DP IDR 50.000",
    company: "BackOrder",
    color: "black",
    category: "latest",
    likes: 27,
  },
  {
    id: 40,
    img: "https://cdn.kyou.id/thumbnail/items/204305-silence-the-paradigmatic-elite-2-ver-shikishi-15x21cm-arknights.jpg",
    title: "[Exclusive Sale] Silence ELite 2 Ver...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 130.000",
    newPrice: "DP IDR 50.000",
    company: "BackOrder",
    color: "white",
    category: "latest",
    likes: 26,
  },
  {
    id: 41,
    img: "https://cdn.kyou.id/thumbnail/items/204306-lone-trail-oil-filled-acrylic-brick-panel-21x12cm-arknights.jpg",
    title: "[Exclusive Sale] Lone Trail Oil-filled...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 370.000",
    newPrice: "DP IDR 100.000",
    company: "BackOrder",
    color: "black",
    category: "latest",
    likes: 25,
  },

  {
    id: 42,
    img: "https://cdn.kyou.id/thumbnail/items/204298-chen-the-holungday-ten-thousand-mountains-shikishi-15x21cm-arknights.jpg",
    title: "[Exclusive Sale] Ch'en the Holungday: Ten...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 130.000",
    newPrice: "DP IDR 50.000",
    company: "BackOrder",
    color: "green",
    category: "latest",
    likes: 24,
  },
  {
    id: 43,
    img: "https://cdn.kyou.id/thumbnail/items/243541-lookup-figure-kita-ikuyo-bocchi-the-rock.jpg",
    title: "[Limited Edition] Lookup Figure Kita...",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "red",
    category: "Limited",
    likes: 23,
  },
  {
    id: 44,
    img: "https://cdn.kyou.id/thumbnail/items/243542-lookup-figure-yamada-ryo-bocchi-the-rock.jpg",
    title: "Lookup Figure Yamada Ryo - Bocchi the Rock!",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "white",
    category: "Bonus",
    likes: 22,
  },
  {
    id: 45,
    img: "https://cdn.kyou.id/thumbnail/items/243540-lookup-figure-hitori-gotoh-bocchi-the-rock.jpg",
    title: "Lookup Figure Hitori Gotoh - Bocchi...",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "blue",
    category: "Bonus",
    likes: 21,
  },
  {
    id: 46,
    img: "https://cdn.kyou.id/thumbnail/items/153621-raiden-shogun-figure-statue-of-her-excellency-the-almighty-narukami-ogosho-god-of-thunder-11cm.jpg",
    title: "[Shukaku SALE] PVC Figure 1/7 Ganyu - ...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 2.450.000",
    newPrice: "IDR 2.319.000",
    company: "ReadyStock",
    color: "black",
    category: "Bonus",
    likes: 20,
  },
  {
    id: 47,
    img: "https://cdn.kyou.id/thumbnail/items/243543-lookup-figure-ijichi-nijika-bocchi-the-rock.jpg",
    title: "Lookup Figure Ijichi Nijika - Bocchi the Rock!",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "black",
    category: "Revive",
    likes: 13,
  },
  {
    id: 48,
    img: "https://cdn.kyou.id/thumbnail/items/113549-limited-production-nendoroid-venti-genshin-impact.jpg",
    title: "[Shukaku Sale] Nendor...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 720.000",
    newPrice: "IDR 699.000",
    company: "ReadyStock",
    color: "red",
    category: "Revive",
    likes: 13,
  },
  {
    id: 49,
    img: "https://cdn.kyou.id/thumbnail/items/163039-limited-production-nendoroid-traveler-lumine-genshin-impact.jpg",
    title: "[Exclusive Sale] Nendoro...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 1.320.000",
    newPrice: "IDR 1.249.000",
    company: "ReadyStock",
    color: "red",
    category: "exclusive",
    likes: 13,
  },

  {
    id: 50,
    img: "https://cdn.kyou.id/thumbnail/items/140557-limited-production-nendoroid-traveler-aether-genshin-impact.jpg",
    title: "[Shukaku SALE] Nendoro...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 820.000",
    newPrice: "IDR 699.000",
    company: "ReadyStock",
    color: "black",
    category: "Revive",
    likes: 13,
  },
  {
    id: 51,
    img: "https://cdn.kyou.id/thumbnail/items/247371-ichiban-kuji-figure-whos-who-one-piece-beast-pirates-tobi-rokusou-e-prize-12cm.jpg",
    title: "Ichiban Kuji Figure Who's Who - One Pi...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 835.000",
    newPrice: "IDR 200.000",
    company: "PreOrder",
    color: "black",
    category: "latest",
    likes: 13,
  },
  {
    id: 52,
    img: "https://cdn.kyou.id/thumbnail/items/247365-ichiban-kuji-figure-gojo-satoru-jujutsu-kaisen-shibuya-incident-vol1-c-prize-19cm.jpg",
    title: "Ichiban Kuji Figure Gojo Satoru - Jujutsu Kai...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 1.550.000",
    newPrice: "DP IDR 550.000",
    company: "PreOrder",
    color: "black",
    category: "latest",
    likes: 13,
  },
  {
    id: 53,
    img: "https://cdn.kyou.id/thumbnail/items/247369-ichiban-kuji-figure-x-drake-one-piece-beast-pirates-tobi-rokusou-c-prize-12cm.jpg",
    title: "Ichiban Kuji Figure X Drake - One Piece Be...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 795.000",
    newPrice: "DP IDR 200.000",
    company: "PreOrder",
    color: "black",
    category: "latest",
    likes: 13,
  },
  {
    id: 54,
    img: "https://cdn.kyou.id/thumbnail/items/247372-ichiban-kuji-figure-black-maria-one-piece-beast-pirates-tobi-rokusou-f-prize-18cm.jpg",
    title: "[Limited Production] Ichiban Kuji Figure...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 2.350.000",
    newPrice: "DP IDR 900.000",
    company: "PreOrder",
    color: "black",
    category: "latest",
    likes: 13,
  },
  {
    id: 55,
    img: "https://cdn.kyou.id/thumbnail/items/234030-pvc-figure-17-klee-spark-knight-ver-genshin-impact.jpg",
    title: "[Exclusive Sale] PVC Figure 1/7 Klee - S...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 2.650.000",
    newPrice: "IDR 2.549.000",
    company: "ReadyStock",
    color: "white",
    category: "exclusive",
    likes: 13,
  },
  {
    id: 56,
    img: "https://cdn.kyou.id/thumbnail/items/102336-hu-tao-ghost-night-lamp-15x14cm-genshin-impact.jpg",
    title: "[Exclusive Sale] Hu Tao Ghost Night...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 580.000",
    newPrice: "IDR 549.000",
    company: "ReadyStock",
    color: "red",
    category: "exclusive",
    likes: 12,
  },

  {
    id: 57,
    img: "https://cdn.kyou.id/thumbnail/items/82990-3rd-release-jumpy-dumpty-klee-mug-genshin-impact-360ml-11x15cm.jpg",
    title: "[Shukaku SALE] Jumpy Dumpty Klee...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 380.000",
    newPrice: "IDR 349.000",
    company: "ReadyStock",
    color: "green",
    category: "exclusive",
    likes: 12,
  },
  {
    id: 58,
    img: "https://cdn.kyou.id/thumbnail/items/247366-ichiban-kuji-figure-gojo-satoru-jujutsu-kaisen-shibuya-incident-vol1-last-one-prize-19cm.jpg",
    title: "[Exclusive Sale] Ichiban Kuji Figure...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 1.950.000",
    newPrice: "DP IDR 1.950.000",
    company: "PreOrder",
    color: "black",
    category: "latest",
    likes: 20,
  },
  {
    id: 59,
    img: "https://cdn.kyou.id/thumbnail/items/243557-lookup-figure-mayuzumi-fuyuko-the-idolmaster-shiny-colors.jpg",
    title: "[Limited Edition] Figure mayuzumi...",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "green",
    category: "Limited",
    likes: 40,
  },
  {
    id: 60,
    img: "https://cdn.kyou.id/thumbnail/items/247367-ichiban-kuji-figure-uruti-one-piece-beast-pirates-tobi-rokusou-a-prize-11cm.jpg",
    title: "[Limited Edition] Ichiban Kuji Figure...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 1.050.000",
    newPrice: "DP IDR 300.000",
    company: "PreOrder",
    color: "black",
    category: "latest",
    likes: 45,
  },

  {
    id: 61,
    img: "https://cdn.kyou.id/thumbnail/items/243556-lookup-figure-serizawa-asahi-the-idolmaster-shiny-colors.jpg",
    title: "[Limited Production] Lookup Figure...",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "white",
    category: "Limited",
    likes: 46,
  },

  {
    id: 62,
    img: "https://cdn.kyou.id/thumbnail/items/106989-feb-2022-release-taroumaru-inazuma-plush-genshin-impact.jpg",
    title: "[Exclusive Sale] Taroumaru Thoma...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 800.000 ",
    newPrice: "IDR 769.000 ",
    company: "ReadyStock",
    color: "green",
    category: "exclusive",
    likes: 56,
  },

  {
    id: 63,
    img: "https://cdn.kyou.id/thumbnail/items/247363-ichiban-kuji-figure-itadori-yuji-jujutsu-kaisen-shibuya-incident-vol1-a-prize-16cm.jpg",
    title: "[Exclusive Sale] Ichiban Kuji Figure...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 560.000",
    newPrice: "DP IDR 100.000",
    company: "PreOrder",
    color: "blue",
    category: "latest",
    likes: 57,
  },

  {
    id: 64,
    img: "https://cdn.kyou.id/thumbnail/items/204312-bloodline-of-combat-tapestry-b-60x40cm-arknigts.jpg",
    title: "[Exclusive Sale] Bloodline of Combat...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 270.000 ",
    newPrice: "IDR 100.000 ",
    company: "BackOrder",
    color: "green",
    category: "latest",
    likes: 60,
  },
  {
    id: 65,
    img: "https://cdn.kyou.id/thumbnail/items/204303-muelsyse-elite-2-ver-shikishi-15x21cm-arknights.jpg",
    title: "[Exclusive Sale] Muelsyse Elite 2 Ver...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 130.000",
    newPrice: "DP IDR 50.000",
    company: "BackOrder",
    color: "red",
    category: "latest",
    likes: 100,
  },
  {
    id: 66,
    img: "https://cdn.kyou.id/thumbnail/items/204304-hoolheyak-elite-2-ver-shikishi-15x21cm-arknights.jpg",
    title: "[Exclusive Sale] Ho'olheyak Elite 2...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 130.000",
    newPrice: "DP IDR 50.000",
    company: "BackOrder",
    color: "black",
    category: "latest",
    likes: 2,
  },
  {
    id: 67,
    img: "https://cdn.kyou.id/thumbnail/items/204305-silence-the-paradigmatic-elite-2-ver-shikishi-15x21cm-arknights.jpg",
    title: "[Exclusive Sale] Silence ELite 2 Ver...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 130.000",
    newPrice: "DP IDR 50.000",
    company: "BackOrder",
    color: "white",
    category: "latest",
    likes: 3,
  },
  {
    id: 68,
    img: "https://cdn.kyou.id/thumbnail/items/204306-lone-trail-oil-filled-acrylic-brick-panel-21x12cm-arknights.jpg",
    title: "[Exclusive Sale] Lone Trail Oil-filled...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 370.000",
    newPrice: "DP IDR 100.000",
    company: "BackOrder",
    color: "black",
    category: "latest",
    likes: 4,
  },

  {
    id: 69,
    img: "https://cdn.kyou.id/thumbnail/items/204298-chen-the-holungday-ten-thousand-mountains-shikishi-15x21cm-arknights.jpg",
    title: "[Exclusive Sale] Ch'en the Holungday: Ten...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 130.000",
    newPrice: "DP IDR 50.000",
    company: "BackOrder",
    color: "green",
    category: "latest",
    likes: 5,
  },
  {
    id: 70,
    img: "https://cdn.kyou.id/thumbnail/items/243541-lookup-figure-kita-ikuyo-bocchi-the-rock.jpg",
    title: "[Limited Edition] Lookup Figure Kita...",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "red",
    category: "Limited",
    likes: 10,
  },
  {
    id: 71,
    img: "https://cdn.kyou.id/thumbnail/items/243542-lookup-figure-yamada-ryo-bocchi-the-rock.jpg",
    title: "Lookup Figure Yamada Ryo - Bocchi the Rock!",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "white",
    category: "Bonus",
    likes: 20,
  },
  {
    id: 72,
    img: "https://cdn.kyou.id/thumbnail/items/243540-lookup-figure-hitori-gotoh-bocchi-the-rock.jpg",
    title: "Lookup Figure Hitori Gotoh - Bocchi...",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "blue",
    category: "Bonus",
    likes: 90,
  },
  {
    id: 73,
    img: "https://cdn.kyou.id/thumbnail/items/153621-raiden-shogun-figure-statue-of-her-excellency-the-almighty-narukami-ogosho-god-of-thunder-11cm.jpg",
    title: "[Shukaku SALE] PVC Figure 1/7 Ganyu - ...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 2.450.000",
    newPrice: "IDR 2.319.000",
    company: "ReadyStock",
    color: "black",
    category: "Bonus",
    likes: 70,
  },
  {
    id: 74,
    img: "https://cdn.kyou.id/thumbnail/items/243543-lookup-figure-ijichi-nijika-bocchi-the-rock.jpg",
    title: "Lookup Figure Ijichi Nijika - Bocchi the Rock!",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "black",
    category: "Revive",
    likes: 60,
  },
  {
    id: 75,
    img: "https://cdn.kyou.id/thumbnail/items/113549-limited-production-nendoroid-venti-genshin-impact.jpg",
    title: "[Shukaku Sale] Nendor...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 720.000",
    newPrice: "IDR 699.000",
    company: "ReadyStock",
    color: "red",
    category: "Revive",
    likes: 60,
  },
  {
    id: 76,
    img: "https://cdn.kyou.id/thumbnail/items/163039-limited-production-nendoroid-traveler-lumine-genshin-impact.jpg",
    title: "[Exclusive Sale] Nendoro...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 1.320.000",
    newPrice: "IDR 1.249.000",
    company: "ReadyStock",
    color: "red",
    category: "exclusive",
    likes: 60,
  },

  {
    id: 77,
    img: "https://cdn.kyou.id/thumbnail/items/140557-limited-production-nendoroid-traveler-aether-genshin-impact.jpg",
    title: "[Shukaku SALE] Nendoro...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 820.000",
    newPrice: "IDR 699.000",
    company: "ReadyStock",
    color: "black",
    category: "Revive",
    likes: 60,
  },
  {
    id: 78,
    img: "https://cdn.kyou.id/thumbnail/items/247371-ichiban-kuji-figure-whos-who-one-piece-beast-pirates-tobi-rokusou-e-prize-12cm.jpg",
    title: "Ichiban Kuji Figure Who's Who - One Pi...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 835.000",
    newPrice: "IDR 200.000",
    company: "PreOrder",
    color: "black",
    category: "latest",
    likes: 60,
  },
  {
    id: 79,
    img: "https://cdn.kyou.id/thumbnail/items/247365-ichiban-kuji-figure-gojo-satoru-jujutsu-kaisen-shibuya-incident-vol1-c-prize-19cm.jpg",
    title: "Ichiban Kuji Figure Gojo Satoru - Jujutsu Kai...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 1.550.000",
    newPrice: "DP IDR 550.000",
    company: "PreOrder",
    color: "black",
    category: "latest",
    likes: 60,
  },
  {
    id: 80,
    img: "https://cdn.kyou.id/thumbnail/items/247369-ichiban-kuji-figure-x-drake-one-piece-beast-pirates-tobi-rokusou-c-prize-12cm.jpg",
    title: "Ichiban Kuji Figure X Drake - One Piece Be...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 795.000",
    newPrice: "DP IDR 200.000",
    company: "PreOrder",
    color: "black",
    category: "latest",
    likes: 60,
  },
  {
    id: 81,
    img: "https://cdn.kyou.id/thumbnail/items/247372-ichiban-kuji-figure-black-maria-one-piece-beast-pirates-tobi-rokusou-f-prize-18cm.jpg",
    title: "[Limited Production] Ichiban Kuji Figure...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 2.350.000",
    newPrice: "DP IDR 900.000",
    company: "PreOrder",
    color: "black",
    category: "latest",
    likes: 1,
  },
];

export default products;

export const getPaginatedData = (data, pageNumber, pageSize) => {
  const startIndex = (pageNumber - 1) * pageSize;
  const endIndex = startIndex + pageSize;
  return data.slice(startIndex, endIndex);
};

export const getTotalPages = (totalItems, pageSize) => {
  return Math.ceil(totalItems / pageSize);
};
