export const section6 = [
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/193863-pvc-figure-17-power-chainsaw-man.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/238226-prisma-wing-figure-unmei-destiny-takt-op-destiny.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/238232-pvc-figure-euphyllia-magenta-tensei-oujo-to-tensai-reijou-no-mahou-kakumei.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/238233-pvc-figure-17-saria-shinka-no-mi-shiranai-uchi-ni-kachigumi-jinsei.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/238234-pvc-figure-17-yat-sen-senkan-shoujo-r.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/238235-pvc-figure-18-kubo-nagisa-kubo-san-wa-mob-wo-yurusanai.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/238240-prisma-figure-eater-illustration-by-neco.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/238541-pvc-figure-17-duramente-uma-musume-pretty-derby.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/238887-pvc-figure-17-sister-edith-illustration-by-shoppai-gensan.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/238894-pvc-figure-17-yoga-girl-yumi-illustration-by-hitomio-16.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/238907-nendoroid-konohoshi-umika-hoshikuzu-telepath.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/238908-pvc-figure-minah-illustration-by-chaesu.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/238910-pvc-figure-16-cheongsam-bunny-girl-xiao-yue.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/238911-pvc-figure-16-skateboard-girl-rin.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/238912-pvc-figure-16-the-temptaion-of-the-succubus-lilia.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/238953-pvc-figure-rise-up-klein-moretti-lord-of-mysteries.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/238954-pvc-figure-pa-15-dance-in-the-ice-sea-ver.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/238955-pvc-figure-lucia-crimson-abyss-apocalyptic-cyan-ver-punishing-gray-raven.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/238956-pvc-figure-karenina-deed-of-snow-leopard-ver-punishing-gray-raven.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/238957-pvc-figure-lydia-illustration-by-dish.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/238959-pvc-figure-17-sakuma-rei-entrancing-myth-ver-ensemble-stars.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/238973-pvc-figure-kagamihara-nadeshiko-yuru-camp-2.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/239340-pvc-figure-dr-illustration-by-neco.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/239341-pvc-figure-nh-01-hito-kaiki-illustration-by-neco.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/239342-pvc-figure-14-atago-stunning-speedster-ver-azur-lane.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/239343-pvc-figure-14-takao-full-throttle-charmer-ver-azur-lane.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/239344-pvc-figure-asa-falslander-illustration-by-neco.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/239345-pvc-figure-shinobi-falslander-illustration-by-neco.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/239346-nendoroid-yamambagiri-kunihiro-touken-ranbu.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
	{
		id: 1,
		src: 'https://cdn.kyou.id/items/239347-pvc-figure-hexe-falslander-illustration-by-neco.jpg',
		alt: 'slide-character-hero',
		description: 'PVC Figure Sakamata Chloe - hololive production',
	},
];
