const products = [
  {
    img: "https://cdn.kyou.id/thumbnail/items/234030-pvc-figure-17-klee-spark-knight-ver-genshin-impact.jpg",
    title: "[Exclusive Sale] PVC Figure 1/7 Klee - S...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    prevPrice: "IDR 2.650.000",
    newPrice: "IDR 2.549.000",
    company: "ReadyStock",
    color: "white",
    category: "exclusive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/102336-hu-tao-ghost-night-lamp-15x14cm-genshin-impact.jpg",
    title: "[Exclusive Sale] Hu Tao Ghost Night...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 580.000",
    newPrice: "IDR 549.000",
    company: "ReadyStock",
    color: "red",
    category: "exclusive",
  },

  {
    img: "https://cdn.kyou.id/thumbnail/items/82990-3rd-release-jumpy-dumpty-klee-mug-genshin-impact-360ml-11x15cm.jpg",
    title: "[Shukaku SALE] Jumpy Dumpty Klee...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 380.000",
    newPrice: "IDR 349.000",
    company: "ReadyStock",
    color: "green",
    category: "exclusive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/247366-ichiban-kuji-figure-gojo-satoru-jujutsu-kaisen-shibuya-incident-vol1-last-one-prize-19cm.jpg",
    title: "[Exclusive Sale] Ichiban Kuji Figure...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 1.950.000",
    newPrice: "DP IDR 1.950.000",
    company: "PreOrder",
    color: "black",
    category: "exclusive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/243557-lookup-figure-mayuzumi-fuyuko-the-idolmaster-shiny-colors.jpg",
    title: "[Limited Edition] Figure mayuzumi...",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "green",
    category: "Limited",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/247367-ichiban-kuji-figure-uruti-one-piece-beast-pirates-tobi-rokusou-a-prize-11cm.jpg",
    title: "[Limited Edition] Ichiban Kuji Figure...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 1.050.000",
    newPrice: "DP IDR 300.000",
    company: "PreOrder",
    color: "black",
    category: "Limited",
  },

  {
    img: "https://cdn.kyou.id/thumbnail/items/243556-lookup-figure-serizawa-asahi-the-idolmaster-shiny-colors.jpg",
    title: "[Limited Production] Lookup Figure...",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "white",
    category: "Limited",
  },

  {
    img: "https://cdn.kyou.id/thumbnail/items/106989-feb-2022-release-taroumaru-inazuma-plush-genshin-impact.jpg",
    title: "[Exclusive Sale] Taroumaru Thoma...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 800.000 ",
    newPrice: "IDR 769.000 ",
    company: "ReadyStock",
    color: "green",
    category: "exclusive",
  },

  {
    img: "https://cdn.kyou.id/thumbnail/items/247363-ichiban-kuji-figure-itadori-yuji-jujutsu-kaisen-shibuya-incident-vol1-a-prize-16cm.jpg",
    title: "[Exclusive Sale] Ichiban Kuji Figure...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 560.000",
    newPrice: "DP IDR 100.000",
    company: "PreOrder",
    color: "blue",
    category: "exclusive",
  },

  {
    img: "https://cdn.kyou.id/thumbnail/items/204312-bloodline-of-combat-tapestry-b-60x40cm-arknigts.jpg",
    title: "[Exclusive Sale] Bloodline of Combat...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 270.000 ",
    newPrice: "IDR 100.000 ",
    company: "BackOrder",
    color: "green",
    category: "exclusive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/204303-muelsyse-elite-2-ver-shikishi-15x21cm-arknights.jpg",
    title: "[Exclusive Sale] Muelsyse Elite 2 Ver...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 130.000",
    newPrice: "DP IDR 50.000",
    company: "BackOrder",
    color: "red",
    category: "exclusive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/204304-hoolheyak-elite-2-ver-shikishi-15x21cm-arknights.jpg",
    title: "[Exclusive Sale] Ho'olheyak Elite 2...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 130.000",
    newPrice: "DP IDR 50.000",
    company: "BackOrder",
    color: "black",
    category: "exclusive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/204305-silence-the-paradigmatic-elite-2-ver-shikishi-15x21cm-arknights.jpg",
    title: "[Exclusive Sale] Silence ELite 2 Ver...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 130.000",
    newPrice: "DP IDR 50.000",
    company: "BackOrder",
    color: "white",
    category: "exclusive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/204306-lone-trail-oil-filled-acrylic-brick-panel-21x12cm-arknights.jpg",
    title: "[Exclusive Sale] Lone Trail Oil-filled...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 370.000",
    newPrice: "DP IDR 100.000",
    company: "BackOrder",
    color: "black",
    category: "exclusive",
  },

  {
    img: "https://cdn.kyou.id/thumbnail/items/204298-chen-the-holungday-ten-thousand-mountains-shikishi-15x21cm-arknights.jpg",
    title: "[Exclusive Sale] Ch'en the Holungday: Ten...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 130.000",
    newPrice: "DP IDR 50.000",
    company: "BackOrder",
    color: "green",
    category: "exclusive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/243541-lookup-figure-kita-ikuyo-bocchi-the-rock.jpg",
    title: "[Limited Edition] Lookup Figure Kita...",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "red",
    category: "Limited",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/243542-lookup-figure-yamada-ryo-bocchi-the-rock.jpg",
    title: "Lookup Figure Yamada Ryo - Bocchi the Rock!",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "white",
    category: "Bonus",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/243540-lookup-figure-hitori-gotoh-bocchi-the-rock.jpg",
    title: "Lookup Figure Hitori Gotoh - Bocchi...",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "blue",
    category: "Bonus",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/153621-raiden-shogun-figure-statue-of-her-excellency-the-almighty-narukami-ogosho-god-of-thunder-11cm.jpg",
    title: "[Shukaku SALE] PVC Figure 1/7 Ganyu - ...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 2.450.000",
    newPrice: "IDR 2.319.000",
    company: "ReadyStock",
    color: "black",
    category: "Bonus",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/243543-lookup-figure-ijichi-nijika-bocchi-the-rock.jpg",
    title: "Lookup Figure Ijichi Nijika - Bocchi the Rock!",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "black",
    category: "Revive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/113549-limited-production-nendoroid-venti-genshin-impact.jpg",
    title: "[Shukaku Sale] Nendor...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 720.000",
    newPrice: "IDR 699.000",
    company: "ReadyStock",
    color: "red",
    category: "Revive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/163039-limited-production-nendoroid-traveler-lumine-genshin-impact.jpg",
    title: "[Exclusive Sale] Nendoro...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 1.320.000",
    newPrice: "IDR 1.249.000",
    company: "ReadyStock",
    color: "red",
    category: "exclusive",
  },

  {
    img: "https://cdn.kyou.id/thumbnail/items/140557-limited-production-nendoroid-traveler-aether-genshin-impact.jpg",
    title: "[Shukaku SALE] Nendoro...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 820.000",
    newPrice: "IDR 699.000",
    company: "ReadyStock",
    color: "black",
    category: "Revive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/247371-ichiban-kuji-figure-whos-who-one-piece-beast-pirates-tobi-rokusou-e-prize-12cm.jpg",
    title: "Ichiban Kuji Figure Who's Who - One Pi...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 835.000",
    newPrice: "IDR 200.000",
    company: "PreOrder",
    color: "black",
    category: "Revive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/247365-ichiban-kuji-figure-gojo-satoru-jujutsu-kaisen-shibuya-incident-vol1-c-prize-19cm.jpg",
    title: "Ichiban Kuji Figure Gojo Satoru - Jujutsu Kai...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 1.550.000",
    newPrice: "DP IDR 550.000",
    company: "PreOrder",
    color: "black",
    category: "Revive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/247369-ichiban-kuji-figure-x-drake-one-piece-beast-pirates-tobi-rokusou-c-prize-12cm.jpg",
    title: "Ichiban Kuji Figure X Drake - One Piece Be...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 795.000",
    newPrice: "DP IDR 200.000",
    company: "PreOrder",
    color: "black",
    category: "Revive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/247372-ichiban-kuji-figure-black-maria-one-piece-beast-pirates-tobi-rokusou-f-prize-18cm.jpg",
    title: "[Limited Production] Ichiban Kuji Figure...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 2.350.000",
    newPrice: "DP IDR 900.000",
    company: "PreOrder",
    color: "black",
    category: "Limited",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/234030-pvc-figure-17-klee-spark-knight-ver-genshin-impact.jpg",
    title: "[Exclusive Sale] PVC Figure 1/7 Klee - S...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 2.650.000",
    newPrice: "IDR 2.549.000",
    company: "ReadyStock",
    color: "white",
    category: "exclusive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/102336-hu-tao-ghost-night-lamp-15x14cm-genshin-impact.jpg",
    title: "[Exclusive Sale] Hu Tao Ghost Night...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 580.000",
    newPrice: "IDR 549.000",
    company: "ReadyStock",
    color: "red",
    category: "exclusive",
  },

  {
    img: "https://cdn.kyou.id/thumbnail/items/82990-3rd-release-jumpy-dumpty-klee-mug-genshin-impact-360ml-11x15cm.jpg",
    title: "[Shukaku SALE] Jumpy Dumpty Klee...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 380.000",
    newPrice: "IDR 349.000",
    company: "ReadyStock",
    color: "green",
    category: "exclusive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/247366-ichiban-kuji-figure-gojo-satoru-jujutsu-kaisen-shibuya-incident-vol1-last-one-prize-19cm.jpg",
    title: "[Exclusive Sale] Ichiban Kuji Figure...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 1.950.000",
    newPrice: "DP IDR 1.950.000",
    company: "PreOrder",
    color: "black",
    category: "exclusive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/243557-lookup-figure-mayuzumi-fuyuko-the-idolmaster-shiny-colors.jpg",
    title: "[Limited Edition] Figure mayuzumi...",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "green",
    category: "Limited",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/247367-ichiban-kuji-figure-uruti-one-piece-beast-pirates-tobi-rokusou-a-prize-11cm.jpg",
    title: "[Limited Edition] Ichiban Kuji Figure...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 1.050.000",
    newPrice: "DP IDR 300.000",
    company: "PreOrder",
    color: "black",
    category: "Limited",
  },

  {
    img: "https://cdn.kyou.id/thumbnail/items/243556-lookup-figure-serizawa-asahi-the-idolmaster-shiny-colors.jpg",
    title: "[Limited Production] Lookup Figure...",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "white",
    category: "Limited",
  },

  {
    img: "https://cdn.kyou.id/thumbnail/items/106989-feb-2022-release-taroumaru-inazuma-plush-genshin-impact.jpg",
    title: "[Exclusive Sale] Taroumaru Thoma...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 800.000 ",
    newPrice: "IDR 769.000 ",
    company: "ReadyStock",
    color: "green",
    category: "exclusive",
  },

  {
    img: "https://cdn.kyou.id/thumbnail/items/247363-ichiban-kuji-figure-itadori-yuji-jujutsu-kaisen-shibuya-incident-vol1-a-prize-16cm.jpg",
    title: "[Exclusive Sale] Ichiban Kuji Figure...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 560.000",
    newPrice: "DP IDR 100.000",
    company: "PreOrder",
    color: "blue",
    category: "exclusive",
  },

  {
    img: "https://cdn.kyou.id/thumbnail/items/204312-bloodline-of-combat-tapestry-b-60x40cm-arknigts.jpg",
    title: "[Exclusive Sale] Bloodline of Combat...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 270.000 ",
    newPrice: "IDR 100.000 ",
    company: "BackOrder",
    color: "green",
    category: "exclusive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/204303-muelsyse-elite-2-ver-shikishi-15x21cm-arknights.jpg",
    title: "[Exclusive Sale] Muelsyse Elite 2 Ver...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 130.000",
    newPrice: "DP IDR 50.000",
    company: "BackOrder",
    color: "red",
    category: "exclusive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/204304-hoolheyak-elite-2-ver-shikishi-15x21cm-arknights.jpg",
    title: "[Exclusive Sale] Ho'olheyak Elite 2...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 130.000",
    newPrice: "DP IDR 50.000",
    company: "BackOrder",
    color: "black",
    category: "exclusive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/204305-silence-the-paradigmatic-elite-2-ver-shikishi-15x21cm-arknights.jpg",
    title: "[Exclusive Sale] Silence ELite 2 Ver...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 130.000",
    newPrice: "DP IDR 50.000",
    company: "BackOrder",
    color: "white",
    category: "exclusive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/204306-lone-trail-oil-filled-acrylic-brick-panel-21x12cm-arknights.jpg",
    title: "[Exclusive Sale] Lone Trail Oil-filled...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 370.000",
    newPrice: "DP IDR 100.000",
    company: "BackOrder",
    color: "black",
    category: "exclusive",
  },

  {
    img: "https://cdn.kyou.id/thumbnail/items/204298-chen-the-holungday-ten-thousand-mountains-shikishi-15x21cm-arknights.jpg",
    title: "[Exclusive Sale] Ch'en the Holungday: Ten...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 130.000",
    newPrice: "DP IDR 50.000",
    company: "BackOrder",
    color: "green",
    category: "exclusive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/243541-lookup-figure-kita-ikuyo-bocchi-the-rock.jpg",
    title: "[Limited Edition] Lookup Figure Kita...",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "red",
    category: "Limited",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/243542-lookup-figure-yamada-ryo-bocchi-the-rock.jpg",
    title: "Lookup Figure Yamada Ryo - Bocchi the Rock!",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "white",
    category: "Bonus",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/243540-lookup-figure-hitori-gotoh-bocchi-the-rock.jpg",
    title: "Lookup Figure Hitori Gotoh - Bocchi...",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "blue",
    category: "Bonus",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/153621-raiden-shogun-figure-statue-of-her-excellency-the-almighty-narukami-ogosho-god-of-thunder-11cm.jpg",
    title: "[Shukaku SALE] PVC Figure 1/7 Ganyu - ...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 2.450.000",
    newPrice: "IDR 2.319.000",
    company: "ReadyStock",
    color: "black",
    category: "Bonus",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/243543-lookup-figure-ijichi-nijika-bocchi-the-rock.jpg",
    title: "Lookup Figure Ijichi Nijika - Bocchi the Rock!",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "black",
    category: "Revive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/113549-limited-production-nendoroid-venti-genshin-impact.jpg",
    title: "[Shukaku Sale] Nendor...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 720.000",
    newPrice: "IDR 699.000",
    company: "ReadyStock",
    color: "red",
    category: "Revive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/163039-limited-production-nendoroid-traveler-lumine-genshin-impact.jpg",
    title: "[Exclusive Sale] Nendoro...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 1.320.000",
    newPrice: "IDR 1.249.000",
    company: "ReadyStock",
    color: "red",
    category: "exclusive",
  },

  {
    img: "https://cdn.kyou.id/thumbnail/items/140557-limited-production-nendoroid-traveler-aether-genshin-impact.jpg",
    title: "[Shukaku SALE] Nendoro...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 820.000",
    newPrice: "IDR 699.000",
    company: "ReadyStock",
    color: "black",
    category: "Revive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/247371-ichiban-kuji-figure-whos-who-one-piece-beast-pirates-tobi-rokusou-e-prize-12cm.jpg",
    title: "Ichiban Kuji Figure Who's Who - One Pi...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 835.000",
    newPrice: "IDR 200.000",
    company: "PreOrder",
    color: "black",
    category: "Revive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/247365-ichiban-kuji-figure-gojo-satoru-jujutsu-kaisen-shibuya-incident-vol1-c-prize-19cm.jpg",
    title: "Ichiban Kuji Figure Gojo Satoru - Jujutsu Kai...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 1.550.000",
    newPrice: "DP IDR 550.000",
    company: "PreOrder",
    color: "black",
    category: "Revive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/247369-ichiban-kuji-figure-x-drake-one-piece-beast-pirates-tobi-rokusou-c-prize-12cm.jpg",
    title: "Ichiban Kuji Figure X Drake - One Piece Be...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 795.000",
    newPrice: "DP IDR 200.000",
    company: "PreOrder",
    color: "black",
    category: "Revive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/247372-ichiban-kuji-figure-black-maria-one-piece-beast-pirates-tobi-rokusou-f-prize-18cm.jpg",
    title: "[Limited Production] Ichiban Kuji Figure...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 2.350.000",
    newPrice: "DP IDR 900.000",
    company: "PreOrder",
    color: "black",
    category: "Limited",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/234030-pvc-figure-17-klee-spark-knight-ver-genshin-impact.jpg",
    title: "[Exclusive Sale] PVC Figure 1/7 Klee - S...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 2.650.000",
    newPrice: "IDR 2.549.000",
    company: "ReadyStock",
    color: "white",
    category: "exclusive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/102336-hu-tao-ghost-night-lamp-15x14cm-genshin-impact.jpg",
    title: "[Exclusive Sale] Hu Tao Ghost Night...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 580.000",
    newPrice: "IDR 549.000",
    company: "ReadyStock",
    color: "red",
    category: "exclusive",
  },

  {
    img: "https://cdn.kyou.id/thumbnail/items/82990-3rd-release-jumpy-dumpty-klee-mug-genshin-impact-360ml-11x15cm.jpg",
    title: "[Shukaku SALE] Jumpy Dumpty Klee...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 380.000",
    newPrice: "IDR 349.000",
    company: "ReadyStock",
    color: "green",
    category: "exclusive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/247366-ichiban-kuji-figure-gojo-satoru-jujutsu-kaisen-shibuya-incident-vol1-last-one-prize-19cm.jpg",
    title: "[Exclusive Sale] Ichiban Kuji Figure...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 1.950.000",
    newPrice: "DP IDR 1.950.000",
    company: "PreOrder",
    color: "black",
    category: "exclusive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/243557-lookup-figure-mayuzumi-fuyuko-the-idolmaster-shiny-colors.jpg",
    title: "[Limited Edition] Figure mayuzumi...",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "green",
    category: "Limited",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/247367-ichiban-kuji-figure-uruti-one-piece-beast-pirates-tobi-rokusou-a-prize-11cm.jpg",
    title: "[Limited Edition] Ichiban Kuji Figure...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 1.050.000",
    newPrice: "DP IDR 300.000",
    company: "PreOrder",
    color: "black",
    category: "Limited",
  },

  {
    img: "https://cdn.kyou.id/thumbnail/items/243556-lookup-figure-serizawa-asahi-the-idolmaster-shiny-colors.jpg",
    title: "[Limited Production] Lookup Figure...",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "white",
    category: "Limited",
  },

  {
    img: "https://cdn.kyou.id/thumbnail/items/106989-feb-2022-release-taroumaru-inazuma-plush-genshin-impact.jpg",
    title: "[Exclusive Sale] Taroumaru Thoma...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 800.000 ",
    newPrice: "IDR 769.000 ",
    company: "ReadyStock",
    color: "green",
    category: "exclusive",
  },

  {
    img: "https://cdn.kyou.id/thumbnail/items/247363-ichiban-kuji-figure-itadori-yuji-jujutsu-kaisen-shibuya-incident-vol1-a-prize-16cm.jpg",
    title: "[Exclusive Sale] Ichiban Kuji Figure...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 560.000",
    newPrice: "DP IDR 100.000",
    company: "PreOrder",
    color: "blue",
    category: "exclusive",
  },

  {
    img: "https://cdn.kyou.id/thumbnail/items/204312-bloodline-of-combat-tapestry-b-60x40cm-arknigts.jpg",
    title: "[Exclusive Sale] Bloodline of Combat...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 270.000 ",
    newPrice: "IDR 100.000 ",
    company: "BackOrder",
    color: "green",
    category: "exclusive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/204303-muelsyse-elite-2-ver-shikishi-15x21cm-arknights.jpg",
    title: "[Exclusive Sale] Muelsyse Elite 2 Ver...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 130.000",
    newPrice: "DP IDR 50.000",
    company: "BackOrder",
    color: "red",
    category: "exclusive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/204304-hoolheyak-elite-2-ver-shikishi-15x21cm-arknights.jpg",
    title: "[Exclusive Sale] Ho'olheyak Elite 2...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 130.000",
    newPrice: "DP IDR 50.000",
    company: "BackOrder",
    color: "black",
    category: "exclusive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/204305-silence-the-paradigmatic-elite-2-ver-shikishi-15x21cm-arknights.jpg",
    title: "[Exclusive Sale] Silence ELite 2 Ver...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 130.000",
    newPrice: "DP IDR 50.000",
    company: "BackOrder",
    color: "white",
    category: "exclusive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/204306-lone-trail-oil-filled-acrylic-brick-panel-21x12cm-arknights.jpg",
    title: "[Exclusive Sale] Lone Trail Oil-filled...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 370.000",
    newPrice: "DP IDR 100.000",
    company: "BackOrder",
    color: "black",
    category: "exclusive",
  },

  {
    img: "https://cdn.kyou.id/thumbnail/items/204298-chen-the-holungday-ten-thousand-mountains-shikishi-15x21cm-arknights.jpg",
    title: "[Exclusive Sale] Ch'en the Holungday: Ten...",
    reviews: {
      text: "BackOrder",
      backgroundColor: "rgb(153, 98, 145)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 130.000",
    newPrice: "DP IDR 50.000",
    company: "BackOrder",
    color: "green",
    category: "exclusive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/243541-lookup-figure-kita-ikuyo-bocchi-the-rock.jpg",
    title: "[Limited Edition] Lookup Figure Kita...",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "red",
    category: "Limited",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/243542-lookup-figure-yamada-ryo-bocchi-the-rock.jpg",
    title: "Lookup Figure Yamada Ryo - Bocchi the Rock!",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "white",
    category: "Bonus",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/243540-lookup-figure-hitori-gotoh-bocchi-the-rock.jpg",
    title: "Lookup Figure Hitori Gotoh - Bocchi...",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "blue",
    category: "Bonus",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/153621-raiden-shogun-figure-statue-of-her-excellency-the-almighty-narukami-ogosho-god-of-thunder-11cm.jpg",
    title: "[Shukaku SALE] PVC Figure 1/7 Ganyu - ...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 2.450.000",
    newPrice: "IDR 2.319.000",
    company: "ReadyStock",
    color: "black",
    category: "Bonus",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/243543-lookup-figure-ijichi-nijika-bocchi-the-rock.jpg",
    title: "Lookup Figure Ijichi Nijika - Bocchi the Rock!",
    reviews: {
      text: "Showcase",
      backgroundColor: "rgb(95, 199, 201)",
    },
    prevPrice: "On Sale Soon",
    company: "Showcase",
    color: "black",
    category: "Revive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/113549-limited-production-nendoroid-venti-genshin-impact.jpg",
    title: "[Shukaku Sale] Nendor...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 720.000",
    newPrice: "IDR 699.000",
    company: "ReadyStock",
    color: "red",
    category: "Revive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/163039-limited-production-nendoroid-traveler-lumine-genshin-impact.jpg",
    title: "[Exclusive Sale] Nendoro...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 1.320.000",
    newPrice: "IDR 1.249.000",
    company: "ReadyStock",
    color: "red",
    category: "exclusive",
  },

  {
    img: "https://cdn.kyou.id/thumbnail/items/140557-limited-production-nendoroid-traveler-aether-genshin-impact.jpg",
    title: "[Shukaku SALE] Nendoro...",
    reviews: {
      text: "Ready Stock",
      backgroundColor: "rgb(65, 183, 116)",
    },
    titleDate: "",
    prevPrice: "IDR 820.000",
    newPrice: "IDR 699.000",
    company: "ReadyStock",
    color: "black",
    category: "Revive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/247371-ichiban-kuji-figure-whos-who-one-piece-beast-pirates-tobi-rokusou-e-prize-12cm.jpg",
    title: "Ichiban Kuji Figure Who's Who - One Pi...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 835.000",
    newPrice: "IDR 200.000",
    company: "PreOrder",
    color: "black",
    category: "Revive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/247365-ichiban-kuji-figure-gojo-satoru-jujutsu-kaisen-shibuya-incident-vol1-c-prize-19cm.jpg",
    title: "Ichiban Kuji Figure Gojo Satoru - Jujutsu Kai...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 1.550.000",
    newPrice: "DP IDR 550.000",
    company: "PreOrder",
    color: "black",
    category: "Revive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/247369-ichiban-kuji-figure-x-drake-one-piece-beast-pirates-tobi-rokusou-c-prize-12cm.jpg",
    title: "Ichiban Kuji Figure X Drake - One Piece Be...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 795.000",
    newPrice: "DP IDR 200.000",
    company: "PreOrder",
    color: "black",
    category: "Revive",
  },
  {
    img: "https://cdn.kyou.id/thumbnail/items/247372-ichiban-kuji-figure-black-maria-one-piece-beast-pirates-tobi-rokusou-f-prize-18cm.jpg",
    title: "[Limited Production] Ichiban Kuji Figure...",
    reviews: {
      text: "PreOrder",
      backgroundColor: "rgb(101, 121, 150)",
    },
    titleDate: "Releases November 2023",
    prevPrice: "IDR 2.350.000",
    newPrice: "DP IDR 900.000",
    company: "PreOrder",
    color: "black",
    category: "Limited",
  },
];

export default products;

export const getPaginatedData = (data, pageNumber, pageSize) => {
  const startIndex = (pageNumber - 1) * pageSize;
  const endIndex = startIndex + pageSize;
  return data.slice(startIndex, endIndex);
};

export const getTotalPages = (totalItems, pageSize) => {
  return Math.ceil(totalItems / pageSize);
};
